"""initial migration

Revision ID: 23fde60075d1
Revises: 
Create Date: 2021-06-17 22:47:59.076853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fde60075d1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'word',
        sa.Column('id', sa.String(length=50), nullable=False),
        sa.Column('word', sa.String(length=400), nullable=False),
        sa.Column('length', sa.Integer(), nullable=False),
        sa.Column('date_created', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_word_date_created'), 'word', ['date_created'], unique=False)
    op.create_index(op.f('ix_word_length'), 'word', ['length'], unique=False)
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_index(op.f('ix_word_length'), table_name='word')
    op.drop_index(op.f('ix_word_date_created'), table_name='word')
    op.drop_table('word')
    # ### end Alembic commands ###
