"""added description field to the word_tag object to give a description of
 how the tag applies to a word

Revision ID: d179e1961def
Revises: 4ebc042881d2
Create Date: 2023-11-17 01:32:03.790003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd179e1961def'
down_revision = '4ebc042881d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.UnicodeText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_tag', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
